---

- hosts:         localhost
  become:        yes
  become_user:   root
  become_method: sudo

  vars:
    dns_domain_name:    "codeadcode.net"
    dns_ttl:            60

  tasks:


  - name: update dns entry
    route53:
      region:           "{{ ansible_ec2_placement_region }}"
      state:            present
      ttl:              "{{ dns_ttl }}"
      zone:             "{{ dns_domain_name }}"
      record:           "bastion.{{ dns_domain_name }}"
      value:            "{{ ansible_ec2_public_ipv4 }}"
      wait:             no


  - name: full update
    yum:
      name:             '*'
      state:            latest


  - name: exec user-data everytime at boot
    replace:
      path:             /etc/cloud/cloud.cfg
      regexp:           '^ - scripts-user$'
      replace:          ' - [scripts-user, always ]'


  - name: check wether pip is already installed
    command:            which pip
    changed_when:       false
    failed_when:        false
    register: pip_installed


  - debug:
      msg:              "pip_installed = {{ pip_installed.rc }}"


  - name: install ansible
    block:

    - name: retrieve get-pip.py script
      get_url:
        url:              https://bootstrap.pypa.io/get-pip.py
        dest:             ~/get-pip.py

    - name: install pip
      shell:              python ~/get-pip.py

    - name: install ansible and dependencies
      pip:
        name:             "{{ item }}"
      loop:
        - ansible
        - boto3
        - paramiko
        - cryptography

    when: pip_installed.rc != 0


  - name: install apache webserver
    yum:
      name:             httpd
      state:            present


  - name: create apache's index page
    template:
      src:              index.html.j2
      dest:             /var/www/html/index.html
      backup:           yes

 
  - name: enable and start apache service
    service:
      name:             httpd
      state:            started
      enabled:          yes


